### ISSUE TITLE
IOError on post install

### ISSUE THREAD

**Issue by midihenry** [rhinstaller/livecd-tools#17]
I used livecd-creator to create a live CD for Cento 6.7 and everything went good.
I then used livecd-iso-to-pxeboot to generate an initrd and vmlinuz files to boot over the network.

I was able to boot on the CentOS liveCD over the network but when I wanted to install the live image on the hard disk I always get this error at the end:
![anaconda_error](https://cloud.githubusercontent.com/assets/7854083/10517244/d6bd9d48-7353-11e5-8d0b-858559141b8c.jpg)

This is the kickstart file that I used with some minor changes:
http://people.centos.org/arrfab/CentOS6/LiveCD-DVD/centos6-liveCD-desktop.cfg

Any help will be appreciated 
Thanks in advance

**Comment by bcl** [comment]
Please open a bug @ bugzilla.redhat.com with the logs from /tmp/*log during the installation attempt attached as individual text/plain attachments. The most likely cause where is something anaconda needs is missing from your livecd.
