### ISSUE TITLE
Enable loop device as installation target

### ISSUE THREAD

**Issue by FGrose** [rhinstaller/livecd-tools#26]
So by ignoring the if isdevloop, except in getdisk(), I was able to install to a loop device backed by a file, such as this,
``dd if=/dev/zero of=myDisc.img bs=1M count=4096``
``losetup /dev/loop0 myDisc.img``

using the following patch,
https://github.com/FGrose/livecdtools/commit/6d2495640241bd889e0f1dcf155f0decf62a7f8a

invoking this command,
``livecd-iso-to-disk.sh --format --msdos --reset-mbr --overlay-size-mb 1024 --home-size-mb 1024 --unencrypted-home Fedora-Live-Workstation-x86_64-23-10.iso /dev/loop0``

I was able to boot the myDisc.img file in GNOME Boxes.
This is an interesting use case.

**Comment by FGrose** [comment]
See also this fix for get_partition1()
https://github.com/FGrose/livecdtools/commit/d755527f424800b4d6ff8e3afbb7be4a64d64c16

**Comment by vpodzime** [comment]
Very nice. But AFAICT, the focus is now on the [livemedia-creator](https://github.com/rhinstaller/lorax/blob/master/src/sbin/livemedia-creator) which is part of the [lorax](https://github.com/rhinstaller/lorax) project. It has support for creation of ``.qcow2`` images and many other formats.

**Comment by bcl** [comment]
Thanks, pushed these 2 to master.
