### ISSUE TITLE
Static Network Configurations Yield Empty resolv.conf files

### ISSUE THREAD

**Issue by torrancew** [rhinstaller/livecd-tools#31]
NOTE: We are using the RHEL 6 version of this tool, but this bug still exists on master as of June 23, 2016.

In debugging an existing process that required we manually inject `resolv.conf` into the images created by `livecd-tools` after running the tools, I uncovered a surprising bug (thanks to my colleague @arrdem for the helpful suggestion):

The SELinux module in `imgcreate` will **truncate** `/etc/resolv.conf` unconditionally:
[RHEL 6 revision](https://github.com/rhinstaller/livecd-tools/blob/rhel6-branch/imgcreate/kickstart.py#L409-L440)
[Master revision](https://github.com/rhinstaller/livecd-tools/blob/rhel6-branch/imgcreate/kickstart.py#L409-L440)

The master revision is a bit more robust, but by my count, the following two lines existing in a kickstart config together will trigger this behavior:
```
selinux --permissive
network --bootproto=static --ip=a.b.c.d --netmask=255.255.255.0 --gateway=w.x.y.z --nameserver=8.8.8.8 --device=eth0 --onboot yes --hostname=hostname.example.com
```

What appears to be happening is this:

* In [creator.py](https://github.com/rhinstaller/livecd-tools/blob/master/imgcreate/creator.py#L748-L754), the order of operations is determined as:
  * ...
  * Network
  * RPMMacro
  * Boot
  * Post
  * SELinux

In the case of using a `network` anaconda directive to configure DNS, [the Network module writes to resolv.conf](https://github.com/rhinstaller/livecd-tools/blob/rhel6-branch/imgcreate/kickstart.py#L354-L366).

Unfortunately, [the SELinux module comes behind and does something eerily similar](https://github.com/rhinstaller/livecd-tools/blob/rhel6-branch/imgcreate/kickstart.py#L411-L417).

The problem here is the use of `w+` as the file mode -- notably, it opens the file in **write** mode, and not **append** mode. Since the SELinux module fires last, it winds up truncating the file. Changing this to `a` will resolve this issue.

**Comment by arrdem** [comment]
🎉

**Comment by rorait** [comment]
Wow, I was going to open a bug for empty resolv.conf and I'm discovering this was fixed in 2016 but still present in RHEL7 today (2021/12, with `python-imgcreate-21.4-2.el7.x86_64`), with no workaround because even with selinux disabled resolv.conf is "processed" anyway before returning (why?!); not even creating /etc/resolv.conf in a `%post` is a workaround, since this code will run after the `%post`.
