### ISSUE TITLE
"testing for presence of *.efi grub binary" can lead to error

### ISSUE THREAD

**Issue by hadess** [rhinstaller/livecd-tools#8]
```
Setting up /EFI/BOOT
/bin/livecd-iso-to-disk: line 1163: [: /media/tgttmp.xQ4Tlx/EFI/BOOT/BOOT.EFI: binary operator expected
Updating boot config file
```

The problem is that this is an i686 image, and in that case, there might be multiple binaries matching the glob in that directory ("mactel" support creates a link from BOOTIA32.EFI to BOOT.EFI).

**Comment by hadess** [comment]
That's the section of code in tools/livecd-iso-to-disk.sh:
```
    # test for presence of *.efi grub binary
    if [ ! -f $(nocase_path "$TGTMNT$EFI_BOOT/BOOT*EFI") ]; then 
```

**Comment by bcl** [comment]
Thanks, please file a bug using bugzilla.redhat.com and include a ls -lR of the media.
